name: data_frame
description: A comprehensive data manipulation and analysis library for Dart, inspired by pandas. Features DataFrame, Series, statistical analysis, and data I/O operations.
version: 1.0.0
homepage: https://github.com/AminMemariani/data-frame
repository: https://github.com/AminMemariani/data-frame
issue_tracker: https://github.com/AminMemariani/data-frame/issues

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  meta: ^1.17.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
