name: dadata
description: A comprehensive data manipulation and analysis library for Dart, inspired by pandas.
version: 1.0.0
homepage: https://github.com/dadata/dadata
repository: https://github.com/dadata/dadata

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.18.0
  csv: ^6.0.0
  meta: ^1.15.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
